services:
  c-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: c-frontend
    volumes:
      - frontend_dist:/app/dist
    networks:
      - hermexus-network

  c-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: c-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - c-frontend
    networks:
      - hermexus-network

include:
  - ./backend/docker-compose.yml

volumes:
  frontend_dist: # Defines the volume for file sharing between containers
