services:
  hermexusapi:
    image: kaiquewalker/hermexusapi:latest
    container_name: c-backend
    build:
      context: .
      dockerfile: hermexusapi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8443
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - hermexus-network

  c-mysql:
    image: mysql:8.0
    container_name: c-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: hermexus_db
    ports:
      - "3306:3306"
    networks:
      - hermexus-network

networks:
  hermexus-network:
    driver: bridge
